apiVersion: v1
kind: Servie
metadata:
  name: virtualonebox-service
  labels:
    app: regapp
spec:
  selector:
    app: regapp

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
